package com.vml.usmc.influencers.model;

//use camel casing
//acronyms should be all caps
public enum MCRCRank {
    PRIVATE, PRIVATE_FIRST_CLASS, LANCE_CORPORAL, CORPORAL, SERGEANT,
    STAFF_SERGEANT, GUNNERY_SERGEANT, MASTER_GUNNERY_SERGEANT, WARRANT_OFFICER,
    CHIEF_WARRANT_OFFICER_2, CHIEF_WARRANT_OFFICER_3, CHIEF_WARRANT_OFFICER_4,
    CHIEF_WARRANT_OFFICER_5, SECOND_LIEUTENANT, FIRST_LIEUTENANT, CAPTAIN,
    MAJOR, LIEUTENANT_COLONEL, COLONEL, MASTER_SERGEANT, 
    
}
